social_media/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.SignInView.as_view(), name="index"),
    url(r'^signup/$',views.SignUpView.as_view(),name="signup"),
    url(r'^logout/$', views.LogOutView.as_view(),name="logout"),
    url(r'^twitter/', include('twitter.urls', namespace="twitter"))
]

twitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
app_name = 'twitter'
urlpatterns = [
    #url(r'', views.ManageAppView.as_view(),name="twitindex"),
    url(r'credentials/$', views.CredentialsView.as_view(),name="credentials"),
    url(r'hashsearch/$', views.HashTagSearchView.as_view(),name="hashsearch"),
    url(r'usersearch/$', views.UserSearchView.as_view(),name="usersearch"),
    url(r'followerslist/$', views.FollowersListView.as_view(),name="followerslist"),
              ]

twitter/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TwitterCredentails(models.Model):
    user = models.ForeignKey(User,related_name="credentials",on_delete=models.CASCADE) #related_name paramater used for creating index on FK and reverse relationship
    access_token = models.CharField(max_length=100,null=True)
    access_secret = models.CharField(max_length=100,null=True)
    consumer_key = models.CharField(max_length=100,null=True)
    consumer_secret = models.CharField(max_length=100,null=True)

twitter/forms.py
from django import forms

class CredentialsForm(forms.Form):

    access_token = forms.CharField(required=True,
                                   label="access token")
    access_secret = forms.CharField(required=True,
                                    label="access secret")
    consumer_key = forms.CharField(required=True,
                                   label="consumer key")
    consumer_secret = forms.CharField(required=True,
                                      label="consumer secret")


    def clean(self):
        clean_data = self.cleaned_data
        print("cleaned_data==",clean_data)

class HashTagSearchForm(forms.Form):
    hash_tag = forms.CharField(required=True,
                               label="Hash Tag")

    def clean(self):
        cleaned_data = self.cleaned_data

class UserSearchForm(forms.Form):
    user_search = forms.CharField(required=True,
                                  label='User Search')

    def clean(self):
        cleaned_data = self.cleaned_data


class FollowersListForm(forms.Form):
    followers_list = forms.CharField(required=True,
                                     label='Get follower list')

    def clean(self):
        cleaned_data = self.cleaned_data

twitter/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
import json

import requests
from django import forms
from django.urls import reverse_lazy
from django.views import generic
from requests_oauthlib import OAuth1
from . import forms as twitforms
from .models import TwitterCredentails
from django.shortcuts import render, render_to_response, HttpResponseRedirect


# Create your views here.

class CredentialsView(generic.FormView):
    template_name = "credentials.html"
    form_class = twitforms.CredentialsForm
    success_url = reverse_lazy("twitter:hashsearch")

    # model = TwitterCredentails


    def form_valid(self, form):
        access_token = self.request.POST['access_token']
        access_secret = self.request.POST['access_secret']
        consumer_key = self.request.POST['consumer_key']
        consumer_secret = self.request.POST['consumer_secret']
        try:
            tc = TwitterCredentails.objects.get(user=self.request.user)
            tc.access_token = access_token,
            tc.access_secret = access_secret,
            tc.consumer_key = consumer_key,
            tc.consumer_secret = consumer_secret
            tc.save()

        except TwitterCredentails.DoesNotExist:
            tc = TwitterCredentails(
                user=self.request.user,
                access_token=access_token,
                access_secret=access_secret,
                consumer_key=consumer_key,
                consumer_secret=consumer_secret)

            tc.save()
        return super(CredentialsView, self).form_valid(form)


class HashTagSearchView(generic.TemplateView):
    template_name = "hashtag_search.html"
    form_class = twitforms.HashTagSearchForm
    success_url = reverse_lazy("twitter:hashsearch")

    # def form_valid(self, form, **kwargs):
    #     return super(HashTagSearchView, self).form_valid(form,)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        print("Hast tag view")
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid() and self.request.POST.get('hash_tag'):
            hash_tag = self.request.POST['hash_tag']
            text_list = []
            url = "https://api.twitter.com/1.1/search/tweets.json?q=" + hash_tag + "&count=2"

            #fetching data from table
            t = TwitterCredentails.objects.get(user=self.request.user)
            t1 = (t.consumer_key.encode("ascii"), t.consumer_secret.encode("ascii"),
                  t.access_token.encode("ascii"), t.access_secret.encode("ascii"))

            try:
                headeroauth = OAuth1(*t1)
                # signature_type='auth_header')
                response = requests.get(url, auth=headeroauth)
                content = json.loads(response.content)
                for comment in content['statuses']:
                    text_list.append(comment.get('text'))
                print( "text===",text_list)
            except Exception as e:
                import traceback
                print(traceback.format_exc())
        return render(request, self.template_name,
                      {'form': form,'text_list':text_list})


class UserSearchView(generic.TemplateView):
    template_name = "user_search.html"
    form_class = twitforms.UserSearchForm
    success_url = reverse_lazy('twitter:usersearch')

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return  render(request, self.template_name, {'form' : form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid() and self.request.POST.get('user_search'):
            user_search = self.request.POST['user_search']
            text_list = []
            url = "https://api.twitter.com/1.1/users/search.json?q=" + user_search + "&count=2"

            #fetching data from table
            c = TwitterCredentails.objects.get(user=self.request.user)
            t1 = (c.consumer_key.encode("ascii"), c.consumer_secret.encode("ascii"),
                  c.access_token.encode("ascii"), c.access_secret.encode("ascii"))

            try:
                headeroauth = OAuth1(*t1)
                # signature_type='auth_header')
                response = requests.get(url, auth=headeroauth)
                content = json.loads(response.content)
                for comment in content['statuses']:
                    text_list.append(comment.get('text'))
                print( "text===",text_list)
            except Exception as e:
                import traceback
                print(traceback.format_exc())
        return render(request, self.template_name,
                      {'form': form,'text_list':text_list})


class FollowersListView(generic.TemplateView):
    template_name = "followers_list.html"
    form_class = twitforms.FollowersListForm
    success_url = reverse_lazy('twitter:followerslist')

    def get(self, request, *args, **kwargs):
        form = self.form_class
        render(request, self.template_name, { 'form' : form })

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid() and self.request.POST.get('followers_list'):
            followers_list = self.request.POST['followers_list']
            text_list = []
            url = 'https://api.twitter.com/1.1/followers/list.json?screen_name='+ followers_list

            #fetching data from table
            cred_t = TwitterCredentails.objects.get(user=self.request.user)
            t = (cred_t.consumer_key.encode("ascii"), cred_t.consumer_secret.encode("ascii"),
                  cred_t.access_token.encode("ascii"), cred_t.access_secret.encode("ascii"))

            try:
                headerauth = OAuth1(*t)
                response = request.get(url, headerauth)
                content = json.loads(response.content)
                for comment in content['statuses']:
                    text_list.append(comment.get('text'))
                print(text_list)
            except:
                import traceback
                print(traceback.format_exc())
            return render(request, self.template_name,
                          {'form' : form, 'text_list' : text_list})

twitter/templates/credentials.html
{% extends "tindex.html" %}

{% block title %}Twitter Credentials{% endblock%}
{%block managetwit%}
<h2>Twitter Credentials</h2>
<form method="Post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock%}

twitter/templates/followers_list.html
{% extends 'tindex.html' %}

{% block title %}Twitter # Followers List Search{% endblock %}

{% block managetwit %}
  <h2>Twitter Followers List</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% if text_list %}
  {% for i in text_list %}
    <p>{{i}}</p>
  {% endfor %}
{% endif %}
{% endblock %}

twitter/templates/hashtag_search.html
{% extends 'tindex.html' %}

{% block title %}Twitter # Tag Search{% endblock %}

{% block managetwit %}
  <h2>Twitter Hash Tag</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% if text_list %}
  {% for i in text_list %}
    <p>{{i}}</p>
  {% endfor %}
{% endif %}
{% endblock %}

twitter/templates/tindex.html
{% extends "index.html" %}
{% block title %}Manage Twitter{% endblock %}
{% block content %}
<div class="row">
    <span class="col-md-12"><a class="pull-right" href="/logout">Log Out</a></span>
</div>
<div class="row">
<div class="panel col-md-2">
    <ul class="list-group ">
      <li class="list-group-item"><a href="{% url 'twitter:credentials' %}">Twitter Credentails</a> </li>
      <li class="list-group-item"><a href="{% url 'twitter:hashsearch' %}">Twitter # tag search</a></li>
      <li class="list-group-item"><a href="{% url 'twitter:usersearch' %}">Twitter # User search</a></li>
        <li class="list-group-item"><a href="{% url 'twitter:followerslist' %}">Twitter # Followers List</a></li>

    </ul>
</div>
<div class="col-md-8">
    {% block managetwit %}
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
        </form>
    {% endblock %}

</div>
</div>
{% endblock %}

twitter/templates/user_search.html
{% extends 'tindex.html' %}

{% block title %}Twitter # Tag Search{% endblock %}

{% block managetwit %}
  <h2>Twitter User Search</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% if text_list %}
  {% for i in text_list %}
    <p>{{i}}</p>
  {% endfor %}
{% endif %}
{% endblock %}